CREATE OR REPLACE view dp_Validaty AS (
SELECT 
	'STG_Orders' AS Table,
	'>1' AS Rule,
	'RowID' AS Column,
	SUM(CASE WHEN "RowID">0 THEN 1 ELSE 0 END ) AS COUNT_VALIDATE_RECORDS,
	SUM(CASE WHEN "RowID">0 THEN 0 ELSE 1 END ) AS COUNT_INVALID_RECORDS
FROM PUBLIC."STG_Orders"

UNION ALL 
SELECT 
	'STG_Orders' AS Table,
	'>1' AS Rule,
	'OrderID' AS Column,
	SUM(CASE WHEN "OrderID">0 THEN 1 ELSE 0 END ) AS COUNT_VALIDATE_RECORDS,
	SUM(CASE WHEN "OrderID">0 THEN 0 ELSE 1 END ) AS COUNT_INVALID_RECORDS
FROM PUBLIC."STG_Orders"

UNION ALL 
SELECT 
	'STG_Orders' AS Table,
	'>2000-01-01' AS Rule,
	'OrderDate' AS Column,
	SUM(CASE WHEN "OrderDate">to_date('2000-01-01','yyyy-mm-dd') THEN 1 ELSE 0 END ) AS COUNT_VALIDATE_RECORDS,
	SUM(CASE WHEN "OrderDate">to_date('2000-01-01','yyyy-mm-dd') THEN 0 ELSE 1 END ) AS COUNT_INVALID_RECORDS
FROM PUBLIC."STG_Orders"

UNION ALL 

SELECT 
	'STG_Orders' AS Table,
	'>0' AS Rule,
	'OrderQuantity' AS Column,
	SUM(CASE WHEN "OrderQuantity">0 THEN 1 ELSE 0 END ) AS COUNT_VALIDATE_RECORDS,
	SUM(CASE WHEN "OrderQuantity">0 THEN 0 ELSE 1 END ) AS COUNT_INVALID_RECORDS
FROM PUBLIC."STG_Orders"


UNION ALL 

SELECT 
	'STG_Orders' AS Table,
	'>0' AS Rule,
	'Sales' AS Column,
	SUM(CASE WHEN "Sales">0 THEN 1 ELSE 0 END ) AS COUNT_VALIDATE_RECORDS,
	SUM(CASE WHEN "Sales">0 THEN 0 ELSE 1 END ) AS COUNT_INVALID_RECORDS
FROM PUBLIC."STG_Orders"

UNION ALL 

SELECT 
	'STG_Orders' AS Table,
	'>=0' AS Rule,
	'Discount' AS Column,
	SUM(CASE WHEN "Discount">=0 THEN 1 ELSE 0 END ) AS COUNT_VALIDATE_RECORDS,
	SUM(CASE WHEN "Discount">=0 THEN 0 ELSE 1 END ) AS COUNT_INVALID_RECORDS
FROM PUBLIC."STG_Orders"


UNION ALL 

SELECT 
	'STG_Orders' AS Table,
	'>0' AS Rule,
	'UnitePrice' AS Column,
	SUM(CASE WHEN "UnitPrice">0 THEN 1 ELSE 0 END ) AS COUNT_VALIDATE_RECORDS,
	SUM(CASE WHEN "UnitPrice">0 THEN 0 ELSE 1 END ) AS COUNT_INVALID_RECORDS
FROM PUBLIC."STG_Orders"


UNION ALL 

SELECT 
	'STG_Orders' AS Table,
	'>0' AS Rule,
	'ShippingCost' AS Column,
	SUM(CASE WHEN "ShippingCost">0 THEN 1 ELSE 0 END ) AS COUNT_VALIDATE_RECORDS,
	SUM(CASE WHEN "ShippingCost">0 THEN 0 ELSE 1 END ) AS COUNT_INVALID_RECORDS
FROM PUBLIC."STG_Orders"


UNION ALL 

SELECT 
	'STG_Orders' AS Table,
	'>Orderdate' AS Rule,
	'ShipDate' AS Column,
	SUM(CASE WHEN "ShipDate">"OrderDate" THEN 1 ELSE 0 END ) AS COUNT_VALIDATE_RECORDS,
	SUM(CASE WHEN "ShipDate">"OrderDate" THEN 0 ELSE 1 END ) AS COUNT_INVALID_RECORDS
FROM PUBLIC."STG_Orders"

)

SELECT * FROM public.dp_Validaty